server:
  port: 8080
  servlet:
    context-path: /cloud

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'